name: Main Job

on: 
  push:
    branches: main
  pull_request:
    branches: main
    
env:
  PROJET_VERSION: 1.0.0
  MAVEN_OPTS: "-DskipTests -Djar.finalName=helloworld-$PROJECT_VERSION -Dmaven.repo.local=/home/runner/work/lib"

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0  
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Construction du JAR
        run: mvn clean package $MAVEN_OPTS

      - name: Cache
        uses: actions/cache@v4.1.2
        with:
          path: ./
          key: helloWorld
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: ${{ github.repository }}
          path: helloworld-java/helloworld-java/target/
        
  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: mvn test
          
