name: Main Job

on: 
  push:
    branches: main

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0  
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Construction du JAR
        run: mvn clean package -DskipTest -Djar.fileName=${{ github.repository }}-${{ vars.PROJECT_VERSION }}
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: ${{ github.repository }}
          path: /helloworld-java/helloworld-java/
        
#  tests:
#      runs-on: ubuntu-latest
#      steps:
#        - name: Run test
#          run: mvn test
          
